global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName


image:
  registry: docker.io
  repository: cnpy/k8s-ssm-agent
  tag: latest
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName


## String to partially override redis.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override redis.fullname template
##
# fullnameOverride:

serviceAccount:
  ## Specifies whether a ServiceAccount should be created
  ##
  create: true
  ## The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the fullname template
  name:

podLabels: {}
nodeSelector:
  kubernetes.io/os: linux
  kubernetes.io/arch: amd64


rbac:
  ## Specifies whether RBAC resources should be created
  ##
  create: true

  role:
    rules:
      - apiGroups:
          - ""
        resources: ["*"]
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - extensions
        resources: ["*"]
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - apps
        resources: ["*"]
        verbs:
          - get
          - list
          - watch