{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "k8s-ssm-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "k8s-ssm-agent.name" . }}
    chart: {{ template "k8s-ssm-agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
{{- if .Values.rbac.role.rules }}
{{ toYaml .Values.rbac.role.rules | indent 2 }}
{{- end -}}
{{- end -}}
